/*
 * Generated by table-gen.py.
 *
 * Inspired by https://github.com/commonmark/cmark/blob/master/src/cmark_ctype.c.
 */


#include <stdint.h>


uint8_t is_num(const unsigned char c);
uint8_t is_ctrl(const unsigned char c);
uint8_t is_alpha(const unsigned char c);
uint8_t is_upper(const unsigned char c);
uint8_t is_lower(const unsigned char c);
uint8_t is_space(const unsigned char c);
uint8_t is_punct(const unsigned char c);
uint8_t is_alphanum(const unsigned char c);
