# Generator for ASCII Character-type table.

# (c) JoBe, 2026


import argparse
import math


def uhex(n: int, bits: int = 2) -> str:
    """
    Format an unsigned positive integer `n` which has
    `bits` bits when returned.
    """

    hx = hex(n)[2:]
    hlen = len(hx)
    return f"0x{"0" * (bits - hlen)}{hx.upper()}"


PRE_C: str =\
"""/*
 * Generated by %s.
 *
 * Inspired by https://github.com/commonmark/cmark/blob/master/src/cmark_ctype.c.
 */


#include <stdint.h>


"""


TABLE_C: str =\
"""#include "%s.h"


static const uint8_t CHAR_TYPES[128] = {
    /*         0x_%s */
"""


LOOKUP_FUNCTION_C: str =\
"""
static uint8_t _get_char_tp(const unsigned char c) {
    if (c >= 0x80) {
        return 0x80;
    };
    return CHAR_TYPES[c];
};



"""


FORMULAS_C: dict[str, str] = {
    "num":      "%s == 0x03",
    "ctrl":     "!(%s & 0x7f)",
    "alpha":    "%s & 0x04",
    "upper":    "%s == 0x05",
    "lower":    "%s == 0x07",
    "space":    "%s & 0x08",
    "punct":    "%s & 0x10",
    "alphanum": "%s & 0x01",
}


def _equal(value: int) -> str:
    return "xori    {i} " + uhex(value) + " r0\n        branch  +2 ~on\n            pshi    0x01\n            ret\n\n        pshi    0x00\n        ret"

def _flag(value: int) -> str:
    return "andi    {i} " + uhex(value) + " r0\n        branch  +2 ~zero\n            pshi    0x01\n            ret\n\n        pshi    0x00\n        ret"

def _nflag(value: int) -> str:
    return "andi    {i} " + uhex(value) + " r0\n        branch  +2 ~on\n            pshi    0x01\n            ret\n\n        pshi    0x00\n        ret"


INPUT_REG: str = "char"
OUTPUT_REG: str = "char_tp"

BASE_H: str = "_TABLE_BASE_H"
BASE_L: str = "_TABLE_BASE_L"

I_DOC: str = "Character as an u8 in (ASCII). Note that 0x80..0xFF are supported too, although they aren't part of ASCII. They will return 0x80, indicating they are controll-characters while using the MSB to indicate being outside the range of ASCII."
O_DOC: str = "Character type identifier. TABLE TBD..."



PRE_JASM: str =\
"""; Generated by %s.
;
; Inspired by https://github.com/commonmark/cmark/blob/master/src/cmark_ctype.c.


#EXT x-rpre-iir


; PRAGMA-ONCE
#IF defined(__%s_MODULE)
#ELSE
    .define {i} auto($8)
    .define {o} auto($8)

    .define _BASE    auto(@8, 0x80)
    .define {base_h} #hi(_BASE)
    .define {base_l} #lo(_BASE)


"""


TABLE_JASM: str =\
"""    ; Initialize the module, loading the table.
    ;
    ; Arguments:
    ; Returns:
    ; Clutters:
    ;     MAR
    .def %s_init
{src}
        ret


"""


LOOKUP_FUNCTION_JASM: str =\
"""    ; Returns the character type identifier for the given ASCII character.
    ;
    ; Arguments:
{i_doc}
    ; Returns:
{o_doc}
    ; Clutters:
    ;     {o}
    ;     {i}
    .def _get_char_tp
        andi    {i} 0x80 {o}
        branch  +2 ~on
            rpre    {base_h} {base_l} {i}
            lod     @00 @00 {o}
        ret



"""


FORMULAS_JASM: dict[str, str] = {
    "num":      _equal(0x03),
    "ctrl":     _nflag(0x7f),
    "alpha":    _flag(0x04),
    "upper":    _equal(0x05),
    "lower":    _equal(0x07),
    "space":    _flag(0x08),
    "punct":    _flag(0x10),
    "alphanum": _flag(0x01)
}


def chartp(idx: int) -> int:
    if idx in (0x09,
               0x0A,
               0x0D,
               0x20):
        return 0x08

    if idx >= 0x21 and idx <= 0x2F:
        return 0x10

    if idx >= 0x30 and idx <= 0x39:
        return 0x03

    if idx >= 0x3A and idx <= 0x40:
        return 0x10

    if idx >= 0x41 and idx <= 0x5A:
        return 0x05

    if idx >= 0x5B and idx <= 0x60:
        return 0x10

    if idx >= 0x61 and idx <= 0x7A:
        return 0x07

    if idx == 0x7f:
        return 0x00

    if idx > 0x7A:
        return 0x10

    return 0x00


def gen_table_c(filename: str) -> str:
    res = TABLE_C
    res %= filename, "  0x_".join(hex(col)[-1] for col in range(0, 16))

    for row in range(0, 8):
        res += "    /* 0x%s_ */ %s,\n"

        row_values: list[int] = []
        for col in range(0, 16):
            row_values.append(chartp(row << 4 | col))

        res %= hex(row)[-1], ", ".join(uhex(val) for val in row_values)

    return res.removesuffix(",\n") + "};\n\n\n"


def gen_check_c(kind: str, formula: str, decl: bool = False) -> str:
    decleration = "uint8_t is_%s(const unsigned char c)"

    if decl:
        return (decleration % kind) + ";\n"

    formula %= "_get_char_tp(c)"

    decleration += " " * (11 - len(kind))
    decleration += " { return %s; };\n"

    return decleration % (kind, formula)



def gen_table_jasm() -> str:
    values: dict[int, int] = {}
    for row in range(0, 8):
        for col in range(0, 16):
            tp = chartp(row << 4 | col)

            if tp != 0:
                values[row << 4 | col] = tp

    src = ""
    for offset, value in values.items():
        src += f"        ldi     {uhex(offset)} {{i}}\n        rpre    {{base_h}} {{base_l}} {{i}}\n        rldi    @00 @00 {uhex(value)}\n"

    return TABLE_JASM.format(src=src)


def gen_check_jasm(kind: str, formula: str, decl: bool = False) -> str:
    decleration = "    .def is_{kind}_tp\n        {src}\n\n\n    .def is_{kind}\n        pop     {i}\n        call    is_{kind}_tp\n        ret\n\n\n"

    if decl:
        return decleration.format(kind=kind,
                                  src="pop     r0\n        pshi    0x00\n        ret",
                                  i=INPUT_REG)

    formula.format(i=INPUT_REG)
    return decleration.format(kind=kind,
                              src=formula,
                              i=INPUT_REG)


def _get_doc(pre: str, maxl: int, doc: str) -> str:
    pre += " " * (maxl - len(pre))
    if maxl % 4 == 0:
        pre += "    "

    length = len(pre)

    lines: list[str] = []
    words = (pre + doc).split(" ")

    line = ""
    while words and words[0] == "":
        words.pop(0)
        line += " "

    while words:
        while words and (len(line + words[0]) < 80):
            line += words.pop(0)
            line += " "

        if not words:
            lines.append(line.rstrip(" "))
            break

        if 80 - len(line) >= (len(line + words[0]) + 1) - 80:
            line += words.pop(0)
            line += " "

        lines.append(line.rstrip(" "))
        line = "    ;"
        line += " " * (length - 5)

    return "\n".join(lines)




def main(filename: str = "ascii", c: bool = True, h: bool = True, j: bool = True) -> None:
    if h:
        res_h = PRE_C % __file__.replace("\\", "/").rsplit("/", 1)[-1]

        for name, formula in FORMULAS_C.items():
            res_h += gen_check_c(name, formula, decl=True)

        with open(f"{filename}.h", "w") as file:
            file.write(res_h)

    if c:
        res_c = PRE_C % __file__.replace("\\", "/").rsplit("/", 1)[-1]
        res_c += gen_table_c(filename)
        res_c += LOOKUP_FUNCTION_C

        for name, formula in FORMULAS_C.items():
            res_c += gen_check_c(name, formula, decl=False)

        with open(f"{filename}.c", "w") as file:
            file.write(res_c)


    if j:
        modname = "gen_" + filename.replace("\\", "/").replace("/", "_").replace("-", "_")

        res_jasm = PRE_JASM
        res_jasm += gen_table_jasm()
        res_jasm += LOOKUP_FUNCTION_JASM

        for name, formula in FORMULAS_JASM.items():
            res_jasm += gen_check_jasm(name, formula, decl=False)

        res_jasm += "\n#DEFINE __%s_MODULE\n"

        res_jasm %= (__file__.replace("\\", "/").rsplit("/", 1)[-1],
                    modname, modname, modname)

        maxl = max(len(f"    ;     *{INPUT_REG} (u8):"), len(f"    ;     *{OUTPUT_REG} (u8):"))
        maxl = math.ceil(maxl / 4) * 4

        with open(f"{filename}.jasm", "w") as file:
            file.write(res_jasm.format(i=INPUT_REG,
                                       o=OUTPUT_REG,
                                       base_h=BASE_H,
                                       base_l=BASE_L,
                                       i_doc=_get_doc(f"    ;     *{INPUT_REG} (u8):",
                                                      maxl, I_DOC),
                                       o_doc=_get_doc(f"    ;     *{OUTPUT_REG} (u8):",
                                                      maxl, O_DOC)))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("filename", default="chartype")

    parser.add_argument("--c", action="store_true")
    parser.add_argument("--h", action="store_true")
    parser.add_argument("--j", "--jasm", action="store_true")

    args = parser.parse_args()

    if not args.c and not args.h and not args.j:
        args.c = True
        args.h = True
        args.j = True

    main(args.filename, args.c, args.h, args.j)
