# Generator for ASCII Character-type table.

# (c) JoBe, 2026


PRE: str =\
"""/*
 * Generated by %s.
 *
 * Inspired by https://github.com/commonmark/cmark/blob/master/src/cmark_ctype.c.
 */


#include <stdint.h>


"""


TABLE: str =\
"""#include "%s.h"


static const uint8_t CHAR_TYPES[128] = {
    /*         0x_%s */
"""


LOOKUP_FUNCTION: str =\
"""
static uint8_t _get_char_tp(const unsigned char c) {
    if (c >= 0x80) {
        return 0x80;
    };
    return CHAR_TYPES[c];
};



"""


FORMULAS: dict[str, str] = {
    "num":      "%s == 0x03",
    "ctrl":     "!(%s & 0x7f)",
    "alpha":    "%s & 0x04",
    "upper":    "%s == 0x05",
    "lower":    "%s == 0x07",
    "space":    "%s & 0x08",
    "punct":    "%s & 0x10",
    "alphanum": "%s & 0x01",
}


def chartp(idx: int) -> int:
    if idx in (0x09,
               0x0A,
               0x0D,
               0x20):
        return 0x08

    if idx >= 0x21 and idx <= 0x2F:
        return 0x10

    if idx >= 0x30 and idx <= 0x39:
        return 0x03

    if idx >= 0x3A and idx <= 0x40:
        return 0x10

    if idx >= 0x41 and idx <= 0x5A:
        return 0x05

    if idx >= 0x5B and idx <= 0x60:
        return 0x10

    if idx >= 0x61 and idx <= 0x7A:
        return 0x07

    if idx == 0x7f:
        return 0x00

    if idx > 0x7A:
        return 0x10

    return 0x00


def uhex(n: int, bits: int = 2) -> str:
    """
    Format an unsigned positive integer `n` which has
    `bits` bits when returned.
    """

    hx = hex(n)[2:]
    hlen = len(hx)
    return f"0x{"0" * (bits - hlen)}{hx.upper()}"


def gen_table(filename: str) -> str:
    res = TABLE
    res %= filename, "  0x_".join(hex(col)[-1] for col in range(0, 16))

    for row in range(0, 8):
        res += "    /* 0x%s_ */ %s,\n"

        row_values: list[int] = []
        for col in range(0, 16):
            row_values.append(chartp(row << 4 | col))

        res %= hex(row)[-1], ", ".join(uhex(val) for val in row_values)

    return res.removesuffix(",\n") + "};\n\n\n"


def gen_check(kind: str, formula: str, decl: bool = False) -> str:
    decleration = "uint8_t is_%s(const unsigned char c)"

    if decl:
        return (decleration % kind) + ";\n"

    formula %= "_get_char_tp(c)"

    decleration += " " * (11 - len(kind))
    decleration += " { return %s; };\n"

    return decleration % (kind, formula)


def main(filename: str = "ascii") -> None:
    res_h = PRE % __file__.replace("\\", "/").rsplit("/", 1)[-1]
    for name, formula in FORMULAS.items():
        res_h += gen_check(name, formula, decl=True)

    res_c = PRE % __file__.replace("\\", "/").rsplit("/", 1)[-1]

    res_c += gen_table(filename)
    res_c += LOOKUP_FUNCTION
    for name, formula in FORMULAS.items():
        res_c += gen_check(name, formula, decl=False)

    with open(f"{filename}.h", "w") as file:
        file.write(res_h)

    with open(f"{filename}.c", "w") as file:
        file.write(res_c)


if __name__ == "__main__":
    main()
